#!/bin/bash

# Chronicle GitHub Repository Setup & Release Commands
# Copy and paste these commands to set up and maintain your Chronicle repository

echo "🚀 Chronicle GitHub Repository Commands"
echo "======================================="

# INITIAL REPOSITORY SETUP (Run once)
echo ""
echo "📦 INITIAL SETUP (Run these commands once to create the repository):"
echo ""
echo "# 1. Initialize Git repository"
echo "git init"
echo ""
echo "# 2. Add all files"
echo "git add ."
echo ""
echo "# 3. Initial commit"
echo "git commit -m 'Initial release: Chronicle v2.0 - Multi-session project documentation system'"
echo ""
echo "# 4. Create GitHub repository (replace YOUR_USERNAME with your GitHub username)"
echo "gh repo create chronicle-kiro-hook --public --description 'Multi-session project documentation system for Kiro AI' --homepage 'https://github.com/YOUR_USERNAME/chronicle-kiro-hook'"
echo ""
echo "# 5. Add remote origin"
echo "git remote add origin https://github.com/YOUR_USERNAME/chronicle-kiro-hook.git"
echo ""
echo "# 6. Push to GitHub"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "# 7. Create initial release with package"
echo "gh release create v2.0 Chronicle-Hook-v2.0-Package.zip --title 'Chronicle v2.0 - Multi-Session Support' --notes 'Initial release with multi-session project documentation, dual themes, and cumulative reporting.'"

echo ""
echo "======================================="
echo ""

# FUTURE UPDATE COMMANDS (Use for updates)
echo "🔄 FUTURE UPDATES (Use these commands when updating Chronicle):"
echo ""
echo "# 1. Stage all changes"
echo "git add ."
echo ""
echo "# 2. Commit with version message (update version number as needed)"
echo "git commit -m 'Release Chronicle v2.1: [DESCRIBE YOUR CHANGES HERE]'"
echo ""
echo "# 3. Push changes"
echo "git push origin main"
echo ""
echo "# 4. Create new tag"
echo "git tag v2.1"
echo ""
echo "# 5. Push tag"
echo "git push --tags"
echo ""
echo "# 6. Create GitHub release (update version and package name)"
echo "gh release create v2.1 Chronicle-Hook-v2.1-Package.zip --title 'Chronicle v2.1' --notes 'Release notes: [DESCRIBE CHANGES]'"

echo ""
echo "======================================="
echo ""

# QUICK UPDATE COMMANDS (One-liners)
echo "⚡ QUICK UPDATE (Copy these one-liners for fast updates):"
echo ""
echo "# Quick commit and push"
echo "git add . && git commit -m 'Update Chronicle v2.1' && git push"
echo ""
echo "# Quick release (update version numbers)"
echo "git tag v2.1 && git push --tags && gh release create v2.1 Chronicle-Hook-v2.1-Package.zip --title 'Chronicle v2.1' --notes 'Updated Chronicle hook'"

echo ""
echo "======================================="
echo ""

# HELPFUL COMMANDS
echo "🛠️  HELPFUL COMMANDS:"
echo ""
echo "# Check repository status"
echo "git status"
echo ""
echo "# View commit history"
echo "git log --oneline"
echo ""
echo "# List all releases"
echo "gh release list"
echo ""
echo "# View repository info"
echo "gh repo view"
echo ""
echo "# Clone repository (for others)"
echo "git clone https://github.com/YOUR_USERNAME/chronicle-kiro-hook.git"

echo ""
echo "======================================="
echo "✅ Ready to go! Replace YOUR_USERNAME with your actual GitHub username."
echo "📝 Update version numbers (v2.1, v2.2, etc.) as you make changes."
echo "🎯 The Chronicle-Hook-v2.0-Package.zip will be attached to releases automatically."